version: '3.9'
services:
  omnichem-frontend-app:
    build: .
    image: omnichem/omnichem-frontend-app:v1.2.2
    container_name: omnichem-frontend-app
    env_file:
      - .env
    ports:
      - 6688:6688
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
