export const suppliersData = [
  {
    id: 1,
    supplierName: "SupName 1",
    city: "Moscow",
    legalEntity: "ООО “Ромашка",
    mainAdvantages: "fast delivery, .....",
    briefDescription: ".....",
  },
  {
    id: 2,
    supplierName: "SupName2",
    city: "Gubkin",
    legalEntity: "ООО “Ромашка",
    mainAdvantages: "fast delivery, .....",
    briefDescription: ".....",
  },
  {
    id: 3,
    supplierName: "SupName3",
    city: "Voronesh",
    legalEntity: "ООО “Ромашка",
    mainAdvantages: "fast delivery, .....",
    briefDescription: ".....",
  },
  {
    id: 4,
    supplierName: "SupName4",
    city: "Kirov",
    legalEntity: "ООО “Ромашка",
    mainAdvantages: "fast delivery, .....",
    briefDescription: ".....",
  },
  {
    id: 5,
    supplierName: "SupName5",
    city: "Kirov",
    legalEntity: "ООО “Ромашка",
    mainAdvantages: "fast delivery, .....",
    briefDescription: ".....",
  },
  {
    id: 6,
    supplierName: "SupName6",
    city: "Kirov",
    legalEntity: "ООО “Ромашка",
    mainAdvantages: "fast delivery, .....",
    briefDescription: ".....",
  },
];
