name: CIFront

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
#      - name: build storybook
#        run: tsc && vite build


  #  - name: Checkout code
   #   uses: actions/checkout@v2
#
 #   - name: Set up Node.js ${{ matrix.node-version }}
  #    uses: actions/setup-node@v2
   #   with:
    #    node-version: ${{ matrix.node-version }}
#
 #   - name: Install dependencies
  #    run: npm ci
#
 #   - name: Build
  #    run: npx tsc --moduleResolution node --jsx react
#      - name: Login to Docker Hub
 #       uses: docker/login-action@v1
  #      with:
   #       username: ${{ secrets.DOCKER_USERNAME }}
    #      password: ${{ secrets.DOCKER_PASSWORD }}
#  
 #     - name: Build and push Docker image
  #      run: |
   #        docker build -t omnichem/omnichem-frontend-app .
    #       docker push omnichem/omnichem-frontend-app:latest
